### PR TITLE
fix(popup): remove amount from OTP msg

### LINKED ISSUE #859: Remove amount from payment confirmation message
- Partial payments confuse users (I tried sending 0.5, why extension says 0.25 was sent)
- Showing amount in case of successful payment doesn't add value much either.

Remove `amount` from payment confirmation message, keeping it limited to: "Thank you for your support".

### PR DESCRIPTION
**Pull request by DarianM**
## Context

Closes #859.

## Changes proposed in this pull request

- Remove amount from payment confirmation message, keeping it limited to: "Thank you for your support".

### CODE REVIEW

File: src/shared/messages.ts [hunk 1]
```diff
@@ -113,8 +113,6 @@ export interface PayWebsitePayload {
 
 export interface PayWebsiteResponse {
   type: 'full' | 'partial';
-  sentAmount: string;
```
Comment (sidvishnoi) [inline src/shared/messages.ts:116]: Might be worth keeping `sentAmount` in response, for better debugging/insights.
