### PR TITLE
fix(content): dispatch `load` event if wallet address is valid

### LINKED ISSUE #365: [BUG] Load event not being triggered
### Steps to reproduce

1. Have a connected wallet
2. Go to a web monetized website that has a listener for the `load` event on the monetization tag
3. If the wallet address is valid, the `load` event is not being dispatched

### Expected result

The `load` event should be triggered if the tag href is a valid wallet address

### Actual result

`load` event no being dispatched.

### Screenshots or videos

_No response_

### Additional context

_No response_

### Operating system

macOS

### Operating system version

_No response_

### Browsers

Chrome, Microsoft Edge, Firefox, Opera

### Browser version

_No response_

### Extension version

alpha 2

### PR DESCRIPTION
**Pull request by raducristianpopa**
## Context

Closes #365.

## Changes proposed in this pull request

Initially I thought there was an error and the `load` event was not correctly dispatched. It looks like we omitted this. Now we dispatch the `load` event if the wallet address is valid.

Additional changes:
- small refactoring for the wallet address check
- update the `checkWalletAddressUrlFormat` function since we do not need to check for SPSP endpoints

### CODE REVIEW

**Comment by raducristianpopa** [comment]
<h2>Extension builds preview</h2>

<table role="table">
<thead>
  <tr>
    <th>Name</th>
    <th>Link</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td align="center">Latest commit</td>
    <td align="center">1b47918ca607a6141c63003e7657262a8f51b2c0</td>
  </tr>
  <tr>
    <td align="center">Latest job logs</td>
    <td align="center"><a href="https://github.com/interledger/web-monetization-extension/actions/runs/9661173418">Run #9661173418</a></td>
  </tr>
  <tr><td align="center">Badge</td><td align="center"><a href="https://github.com/interledger/web-monetization-extension/suites/25285678025/artifacts/1635554562">Download</a></td></tr><tr><td align="center">Badge</td><td align="center"><a href="https://github.com/interledger/web-monetization-extension/suites/25285678025/artifacts/1635554563">Download</a></td></tr>
</tbody>
</table>

File: src/content/utils.ts [hunk 1]
```diff
@@ -1,55 +1,32 @@
...
-        JSON.stringify({
-          hash: url.hash,
-          search: url.search,
-          port: url.port,
-          username: url.username,
-          password: url.password
-        })
+  if (hash || search || port || username || password) {
+    throw new WalletAddressFormatError(
+      `Wallet address URL must not contain query/fragment/port/username/password elements. Received: ${JSON.stringify({ hash, search, port, username, password })}`
```
Comment (sidvishnoi) [inline src/content/utils.ts:27]: Perhaps we can do a comparison with what we allow, instead of showing the technical hash, search etc parts? 
For example: `if (urlWeAreOkWith !== UrlThatUserGave) throw UserGaveExtraStuff`

File: src/content/utils.ts [hunk 2]
```diff
@@ -1,55 +1,32 @@
...
   try {
-    url = new URL(httpUrl)
-    if (!url.protocol.match(/https?:/)) {
-      const spec = urlOnly ? '' : 'either a payment pointer or '
-      // noinspection ExceptionCaughtLocallyJS
-      throw new PaymentEndpointError(
-        `SPSP endpoint must be specified as ${spec}fully resolved https:// url, ` +
-          `got ${JSON.stringify(pointerOrUrl)} `
+    url = new URL(walletAddressUrl)
+    if (url.protocol !== 'https:') {
```
Comment (sidvishnoi) [inline src/content/utils.ts:7]:
```suggestion
    if (!ALLOWED_PROTOCOLS.includes(url.protocol)) {
```

File: src/content/utils.ts (hunk 1 above)
Comment (sidvishnoi) [reply src/content/utils.ts:27]: or, we can just accept and ignore rest of the parts (when saving) if we get the same result anyway?

Comment (raducristianpopa) [reply src/content/utils.ts:27]: > Perhaps we can do a comparison with what we allow, instead of showing the technical hash, search etc parts?
For example: if (urlWeAreOkWith !== UrlThatUserGave) throw UserGaveExtraStuff

Would attaching a link to the Open Payments documentation work?

> or, we can just accept and ignore rest of the parts (when saving) if we get the same result anyway?

I think we should be strict about the format to not cause misconceptions.

File: src/content/utils.ts (hunk 2 above)
Comment (raducristianpopa) [reply src/content/utils.ts:7]: The wallet address should always be served under `https:`.

Comment (sidvishnoi) [reply src/content/utils.ts:7]: I meant if in dev we want to use a localhost Rafiki.

File: src/content/utils.ts (hunk 1 above)
Comment (sidvishnoi) [reply src/content/utils.ts:27]: We can edit the input to what we want and warn the user ("heads up, you pasted this but wallet address is just the URL that looks like this"); instead of adding friction to this user input.
IMO, we should even let input `$paymentPointer` (as can be copied from rafiki.money at present), to reduce this friction.

I think adding link to documentation is still technical enough for users, as technical as showing the `{query,fragment,port}` etc.

Comment (sidvishnoi) [reply src/content/utils.ts:27]: Let's do that as a follow-up... reducing friction. For now, let's use an error message that gives most info.

Comment (sidvishnoi) [reply src/content/utils.ts:27]: Ah! Never mind! I thought it was the input in popup!

File: src/content/services/monetizationTagManager.ts [hunk 3]
```diff
@@ -496,47 +506,30 @@ export class MonetizationTagManager extends EventEmitter {
...
+        throw new Error(
+          `Could not retrieve wallet address information for ${JSON.stringify(walletAddressUrl)}.`
+        )
+      }
 
+      this.dispatchLoadEvent(tag)
+      return response.payload
+    } catch (e) {
+      this.logger.error(e)
+      this.dispatchErrorEvent(tag)
```
Comment (sidvishnoi) [inline src/content/services/monetizationTagManager.ts:532]: Should include error message in this (can dispatch `new ErrorEvent('error', {message})`), instead of logging from content script (optional instead, ok to show error twice I think).

Comment (sidvishnoi) [reply src/content/services/monetizationTagManager.ts:532]: Looks like ErrorEvent can't be transmitted across content script boundary. Using CustomElement like we do for `monetization` event should work.

```diff
diff --git a/src/content/polyfill.ts b/src/content/polyfill.ts
index acd8c65..7c03428 100644
--- a/src/content/polyfill.ts
+++ b/src/content/polyfill.ts
@@ -122,4 +122,19 @@ import type { MonetizationEventPayload } from '@/shared/messages'
     },
     { capture: true }
   )
+
+  window.addEventListener(
+    '__wm_ext_error',
+    (event: CustomEvent<{ message: string; error: Error }>) => {
+      if (!event.target) return
+      if (!(event.target instanceof HTMLElement)) return
+      event.target.dispatchEvent(
+        new ErrorEvent('error', {
+          message: event.detail.message,
+          error: event.detail.error
+        })
+      )
+    },
+    { capture: true }
+  )
 })()
diff --git a/src/content/services/monetizationTagManager.ts b/src/content/services/monetizationTagManager.ts
index 8105c50..b5e8a8c 100644
--- a/src/content/services/monetizationTagManager.ts
+++ b/src/content/services/monetizationTagManager.ts
@@ -69,8 +69,13 @@ export class MonetizationTagManager extends EventEmitter {
     tag.dispatchEvent(new Event('load'))
   }
 
-  private dispatchErrorEvent(tag: MonetizationTag) {
-    tag.dispatchEvent(new Event('error'))
+  private dispatchErrorEvent(tag: MonetizationTag, error: Error) {
+    tag.dispatchEvent(
+      new CustomEvent('__wm_ext_error', {
+        detail: mozClone({ message: error.message, error }, this.document),
+        bubbles: true
+      })
+    )
   }
 
   dispatchMonetizationEvent({ requestId, detail }: MonetizationEventPayload) {
@@ -529,7 +534,7 @@ export class MonetizationTagManager extends EventEmitter {
       return response.payload
     } catch (e) {
       this.logger.error(e)
-      this.dispatchErrorEvent(tag)
+      this.dispatchErrorEvent(tag, e as Error)
       return null
     }
   }
```
