### PR TITLE
fix(background): don't create unncessary payments & events

### LINKED ISSUE #460: Do not resend monetization event on focus change
### Context

_TBD_

### Todos

_TBD_

### PR DESCRIPTION
**Pull request by raducristianpopa**
## Context

- Closes #460
- Closes https://github.com/interledger/web-monetization-extension/issues/468

## Changes proposed in this pull request

- Ensure not to trigger extra/unnecessary/stray payments on focus change
   - Don't use `await sleep()`, but clear timers/intervals on stop. `sleep` and related state management leads to race conditions and stray runs.
- Don't resend overpaying (existing) monetization event on disable/enable and on focus change

### CODE REVIEW

**Comment by raducristianpopa** [comment]
<h2>Extension builds preview</h2>

<table role="table">
<thead>
  <tr>
    <th>Name</th>
    <th>Link</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td align="center">Latest commit</td>
    <td align="center">cc198dc67f8637b6ee76ca4b50628430f9ccb6c8</td>
  </tr>
  <tr>
    <td align="center">Latest job logs</td>
    <td align="center"><a href="https://github.com/interledger/web-monetization-extension/actions/runs/10198758145">Run #10198758145</a></td>
  </tr>
  <tr><td align="center">Badge</td><td align="center"><a href="https://github.com/interledger/web-monetization-extension/suites/26687463402/artifacts/1764731672">Download</a></td></tr><tr><td align="center">Badge</td><td align="center"><a href="https://github.com/interledger/web-monetization-extension/suites/26687463402/artifacts/1764731673">Download</a></td></tr>
</tbody>
</table>

File: src/background/services/paymentSession.ts [hunk 1]
```diff
@@ -179,15 +199,38 @@ export class PaymentSession {
...
-      await this.payContinuous()
-      await sleep(this.intervalInMs)
+    // Uncomment this after we perform the Rafiki test and remove the leftover
+    // code below.
+    //
+    // if (this.active && !this.isDisabled) {
+    //   this.timeout = setTimeout(() => {
+    //     void this.payContinuous()
+    //
+    //     this.interval = setInterval(() => {
```
Comment (dianafulga) [inline src/background/services/paymentSession.ts:211]: I think this will run even when the session becomes inactive or disavled

**Review by sidvishnoi — APPROVED** [review]

**Review by dianafulga — APPROVED** [review]
