### PR TITLE
fix(background): use correct intent in `completeGrant` for add funds

### LINKED ISSUE #536: [BUG] Invalid interaction intent when redirecting to welcome screen after adding more funds
### Steps to reproduce

1. Run out of funds
2. Add more funds
3. Accept the grant when redirect to the IdP page.
4. The welcome screen is displaying the wrong message: `Your wallet is now successfully connected to the extension.`

### Expected result

The finish URL `intent` query parameter should be set to `funds` instead of `connect`.

### Actual result

The finish URL `intent` query parameter is set to `connect` instead of `funds`, therefore the wrong message is displayed on the welcome screen.

### Screenshots or videos

_No response_

### Additional context

_No response_

### Operating system

macOS

### Operating system version

_No response_

### Browsers

Chrome, Microsoft Edge, Firefox, Opera

### Browser version

_No response_

### Extension version

beta

### PR DESCRIPTION
**Pull request by raducristianpopa**
## Context

Closes #536.

### CODE REVIEW

File: src/background/services/openPayments.ts [hunk 1]
```diff
@@ -359,7 +359,12 @@ export class OpenPaymentsService {
       'recurringGrant'
     ])
 
-    await this.completeGrant(amount, walletAddress!, recurring)
+    await this.completeGrant(
+      amount,
+      walletAddress!,
+      recurring,
+      InteractionIntent.FUNDS
```
Comment (sidvishnoi) [inline src/background/services/openPayments.ts:366]: Let's make that 4th param required.

**Review by sidvishnoi — APPROVED** [review]

**Review by sidvishnoi — APPROVED** [review]
