### PR TITLE
fix(background): if wallet not connected, display default icon

### LINKED ISSUE #505: [BUG] Default icon should be displayed if wallet is not connected
Expected behaviour:
When wallet is not connected, the extension should display the default icon on any website

Current behaviour:
When wallet is not connected, the extension should display the no link enabled icon on any website

https://github.com/user-attachments/assets/34eff9fe-83b3-4ed0-8462-1c65190eceeb

### PR DESCRIPTION
**Pull request by dianafulga**
Fixes #505

### CODE REVIEW

**Comment by raducristianpopa** [comment]
<h2>Extension builds preview</h2>

<table role="table">
<thead>
  <tr>
    <th>Name</th>
    <th>Link</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td align="center">Latest commit</td>
    <td align="center">da5cc85a9109c6dd679049c8cc3dea5af2402a03</td>
  </tr>
  <tr>
    <td align="center">Latest job logs</td>
    <td align="center"><a href="https://github.com/interledger/web-monetization-extension/actions/runs/10418248921">Run #10418248921</a></td>
  </tr>
  <tr><td align="center">Badge</td><td align="center"><a href="https://github.com/interledger/web-monetization-extension/suites/27248423798/artifacts/1819504153">Download</a></td></tr><tr><td align="center">Badge</td><td align="center"><a href="https://github.com/interledger/web-monetization-extension/suites/27248423798/artifacts/1819504155">Download</a></td></tr>
</tbody>
</table>

File: src/background/services/tabEvents.ts [hunk 1]
```diff
@@ -129,18 +134,22 @@ export class TabEvents {
 
   private getIconAndTooltip({
     enabled,
+    connected,
     state,
     isTabMonetized,
     hasTabAllSessionsInvalid
   }: {
     enabled: Storage['enabled']
+    connected: boolean
```
Comment (sidvishnoi) [inline src/background/services/tabEvents.ts:143]:
```suggestion
    connected: Storage['connected']
```

**Review by raducristianpopa — APPROVED** [review]

**Review by sidvishnoi — APPROVED** [review]
Thank you @dianafulga!
